export const carsData = [
  {
    id: "1",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/ford/focus.jpg",
    make: "Toyota",
    model: "Camry",
    year: 2018,
    price: 20000,
  },
  {
    id: "2",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/fiat/panda.jpg",
    make: "Honda",
    model: "Civic",
    year: 2020,
    price: 18500,
  },
  {
    id: "3",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/fiat/500.jpg",
    make: "Ford",
    model: "Mustang",
    year: 2019,
    price: 30000,
  },
  {
    id: "4",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/opel/mokka.jpg",
    make: "Chevrolet",
    model: "Silverado",
    year: 2021,
    price: 35000,
  },
  {
    id: "5",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/jeep/grand_cherokee.jpg",
    make: "BMW",
    model: "3 Series",
    year: 2022,
    price: 40000,
  },
  // Additional cars...
  {
    id: "6",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/ford/escape.jpg",
    make: "Tesla",
    model: "Model S",
    year: 2021,
    price: 80000,
  },
  {
    id: "7",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/toyota/rav_4.jpg",
    make: "Audi",
    model: "A4",
    year: 2017,
    price: 25000,
  },
  {
    id: "8",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/ford/mondeo.jpg",
    make: "Mercedes-Benz",
    model: "C-Class",
    year: 2020,
    price: 45000,
  },
  {
    id: "9",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/hyundai/elantra.jpg",
    make: "Nissan",
    model: "Altima",
    year: 2019,
    price: 22000,
  },
  {
    id: "10",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/audi/a3.jpg",
    make: "Volkswagen",
    model: "Golf",
    year: 2016,
    price: 15000,
  },
  // More cars...
  {
    id: "11",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/toyota/corolla.jpg",
    make: "Toyota Corolla",
    model: "Golf",
    year: 2016,
    price: 15000,
  },
  {
    id: "12",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/dodge/caravan.jpg",
    make: "Dodge Grand Caravan",
    model: "Golf",
    year: 2021,
    price: 15000,
  },
  {
    id: "13",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/ford/galaxy.jpg",
    make: "Ford Galaxy",
    model: "Ford",
    year: 2021,
    price: 15000,
  },
  {
    id: "14",
    url: "https://cdn2.rcstatic.com/images/car_images/new_images/opel/zafira.jpg",
    make: "Opel Zafira",
    model: "Ford",
    year: 2021,
    price: 18000,
  },
];
